# Generated by Django 4.1.5 on 2023-01-28 08:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Культура')),
            ],
            options={
                'verbose_name': 'Культуры',
                'verbose_name_plural': 'Культура',
                'db_table': 'culture',
            },
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя фермера')),
            ],
            options={
                'verbose_name': 'Фермеры',
                'verbose_name_plural': 'Фермер',
                'db_table': 'farmer',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_season', models.PositiveIntegerField(verbose_name='Сезон')),
            ],
            options={
                'verbose_name': 'Сезоны',
                'verbose_name_plural': 'Сезон',
                'db_table': 'season',
            },
        ),
        migrations.CreateModel(
            name='Plots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contour', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
                ('culture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_cultures', to='app.culture')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_plots', to='app.farmer')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_seasons', to='app.season')),
            ],
            options={
                'verbose_name': 'Поле',
                'verbose_name_plural': 'Поле',
                'db_table': 'plots',
            },
        ),
    ]
